// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type PInput struct {
	Name      string `json:"name"`
	Type      string `json:"type"`
	Available bool   `json:"available"`
}

type PType struct {
	ID        *string `json:"id"`
	Name      *string `json:"name"`
	Type      *string `json:"type"`
	Available *bool   `json:"available"`
}

type ProductInput struct {
	Name      string `json:"name"`
	Type      string `json:"type"`
	Available bool   `json:"available"`
}

type ProductType struct {
	ID        *string `json:"id"`
	Name      *string `json:"name"`
	Type      *string `json:"type"`
	Available *bool   `json:"available"`
}
